CREATE TABLE ITEMS (
  RECEIPT INT NOT NULL,
  ORDINAL INT NOT NULL,
  ITEM VARCHAR(20) NOT NULL,
  PRIMARY KEY (RECEIPT, ORDINAL),
  FOREIGN KEY (RECEIPT) REFERENCES RECEIPTS(RECEIPTNUMBER),
  FOREIGN KEY (ITEM) REFERENCES GOODS(ID)
);

