CREATE TABLE CUSTOMERS (
  ID INT NOT NULL,
  LASTNAME VARCHAR(50),
  FIRSTNAME VARCHAR(50),
  PRIMARY KEY (ID)
);
CREATE TABLE ITEMS (
  RECEIPT INT NOT NULL,
  ORDINAL INT NOT NULL,
  ITEM VARCHAR(20) NOT NULL,
  PRIMARY KEY (RECEIPT, ORDINAL),
  FOREIGN KEY (RECEIPT) REFERENCES RECEIPTS(RECEIPTNUMBER),
  FOREIGN KEY (ITEM) REFERENCES GOODS(ID)
);

CREATE TABLE GOODS (
  ID VARCHAR(20) NOT NULL,
  FLAVOR VARCHAR(50),
  FOOD VARCHAR(50),
  PRICE DECIMAL(6,2),
  PRIMARY KEY (ID)
);

CREATE TABLE RECEIPTS (
  RECEIPTNUMBER INT NOT NULL,
  DATE DATE,
  CUSTOMERID INT NOT NULL,
  PRIMARY KEY (RECEIPTNUMBER),
  FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(ID)
);
